name: Test Find Lowest Number

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Test Case 1 - Multiple Numbers
      run: |
        echo "Running test case 1..."
        python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
        echo "Content of test1_output.txt:"
        cat test1_output.txt
        echo "Content of test_data/test1_expected.txt:"
        cat test_data/test1_expected.txt
        echo "Running diff..."
        diff test1_output.txt test_data/test1_expected.txt
    
    - name: Test Case 2 - Single Number
      run: |
        echo "Running test case 2..."
        python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
        echo "Content of test2_output.txt:"
        cat test2_output.txt
        echo "Content of test_data/test2_expected.txt:"
        cat test_data/test2_expected.txt
        echo "Running diff..."
        diff test2_output.txt test_data/test2_expected.txt
    
    - name: Test Case 3 - Empty File
      run: |
        echo "Running test case 3..."
        python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
        echo "Content of test3_output.txt:"
        cat test3_output.txt
        echo "Content of test_data/test3_expected.txt:"
        cat test_data/test3_expected.txt
        echo "Running diff..."
        diff test3_output.txt test_data/test3_expected.txt
